# This is an example of ansible playbook written in YMAL

# YAML FILE STARTS WITH THREE --- DASHES(---)
---
- hosts: web
# host is to define the name of your host machine, group or all servers
# in this example we are targeting server called web

  gather_facts: yes
# gethering facts before performing any tasks

  become: true
# become is used to get root permission to perform any tasks that may require admin access

  tasks:
#Tasks are executed in order, one at a time, against all Servers matched by the host pattern
# Every task should have a name, which is included in the output from running the playbook
# The goal of each task is to execute a module, with very specific arguments.

#  - name: copy app folder in
#    copy:
#      src: /home/ubuntu/app
#      dest: /home/ubuntu/app

  - name: Install nginx
  # we are installing nginx on our web server

    apt: pkg=nginx state=present
    notify:
    - restart nginx

  - name: Enable nginx during boot
    service: name=nginx  state=started enabled=yes

  - name: Install git
    apt: pkg=git state=present

  - name: Install python
    apt : pkg=python state=present

  - name: Install Node
    shell: |
      curl -sL https://deb.nodesource.com/setup_12.x | sudo -E bash -

  - name: Install node part 2
    apt: pkg=nodejs state=present

  - name: apt get update
    apt: update_cache=yes force_apt_get=yes cache_valid_time=3600

#  - name: Install NPM
#    apt:
#     name: npm
#     state: present


  - name: Install PM2
    npm:
      name: pm2
      global: yes


#  - name: stop app
#    command: pm2 stop app.js
#    args:
#      chdir: /home/ubuntu/app

#  - name: start app
#    command: pm2 start app.js
#    args:
#      chdir: /home/ubuntu/app

  - name: Setup Env Var DB_HOST
    shell: echo 'export DB_HOST=mongodb://192.168.10.20:27017/posts' >> ~/.bashrc
    become: yes
    become_user: vagrant


  handlers:
          - name: restart nginx
            service: name=nginx state=restarted
